### ISSUE TITLE
NativeScript Angular - Styles not applied in app.component

### ISSUE THREAD

**Issue by MaxiSonntag** [NathanaelA/nativescript-platform-css#22]
The plugin works just fine in regular components in NativeScript with Angular, but not in `app.component`.

`require( "nativescript-platform-css" );` is set in `main.ts` file, however styles in `app.component.css` are not applied to `app.component.html` layout. Same if required in `app.module.ts`. When using the same code in a placeholder component it works like a charm.

I'm using `TabView` as root navigation, therefore it would be nice if it was possible to set platform specific syles here as well.

**Comment by rynop** [comment]
I have what I think is a related problem.  I use [SASS for NativeScript](https://docs.nativescript.org/angular/ui/theme#sass-usage) and the following does **not** work in my `_app-common.scss`

```css
.tablet :host {
    .btn,
    button {
        font-size: 24;
    }
}
```

The exact same css put into my `mycomp.component.scss` works fine.

Painful because styles I'd like applied throughout my app I have to copy/paste in every components `.scss` (or use an import).

**Comment by NathanaelA** [comment]
Check the CSS generated and make sure the :host is being applied.   If Sass is stripping it out; that would be the reason.

**Comment by rynop** [comment]
Thanks for the idea, but when the `scss` compiles it leaves `:host` in the resulting `css`.

`_app-common.scss`:

```css
.far {
  font-family: 'Font Awesome 5 Free', fa-regular-400;
}

.fab {
  font-family: 'Font Awesome 5 Brands', fa-brands-400;
}

.fas {
  font-family: 'Font Awesome 5 Free Solid', fa-solid-900;
}

.action-link {
  color: $btn-color;
}

.tablet :host {
    .btn,
    button {
        font-size: 24;
    }
}
```

my `app.ios.scss` looks like this:

```scss
// Import app variables
@import 'app-variables';

// Import the theme’s main ruleset - both index and platform specific.
@import '~nativescript-theme-core/scss/index';
@import '~nativescript-theme-core/scss/platforms/index.ios';

// Import common styles
@import 'app-common';

// Place any CSS rules you want to apply only on iOS here
```

It compiles to `app.ios.css` correctly:

```css
...
.tablet :host .btn,
.tablet :host button {
  font-size: 24;
}
```

However this is not picked up in any of my components.  If I put the `.tablet :host {...` into my component specific `.scss` it compiles down to the same `.css` and everything works fine.  Also of note, the other rules in `_app-common.scss` are correctly working throughout all my components.

@NathanaelA any ideas? I haven't looked at your code yet to see how the device (ex: `.tablet`) injection is working.

My guess is this is an issue completely outside of your plugin, so don't waste your time on this if you don't know off the top of your head.

**Comment by NathanaelA** [comment]
Hmm, that is weird.   .tablet is injected at the top level `page` element.   I have seen another bug that if you are using a `tabview` as the top element you have issues since the code looks for a page element, never finds it so it never sets it.      I need to spend some time with the plugin and making sure all top level elements are supported (`Page` used to be the only valid top level element, in the latest versions of NS now there can be several types...  So this is a known issue; just haven't had time to test and fix it... )

**Comment by rynop** [comment]
AFAIK Angular running on NativeScript does not have a `<page>` XML element.

`main.ts` loads `./app/app.module` which loads and renders `app.component.ts`.  In my app, `app.component.html` is:

```xml
<page-router-outlet></page-router-outlet>
```

And the 1st (root aka `/`) component that is rendered in this router-outlet is my `home.component.html`:

```xml
<ActionBar title="Home" class="action-bar" visability="collapsed"></ActionBar>
<GridLayout rows="2*,2*,4*" class="page">
...
```

I know the `tablet` is being injected correctly, because if I put the following into `home.component.scss` it works as expected:

```scss
.tablet :host {
    .btn,
    button {
        font-size: 24;
    }
}
```

Totally understand not testing and fixing this one.  It is easy to work around, and like I said its prob not problem with your plugin.  Just leaving details here incase someone else runs into it.
